// Returns the current player level
native ls_get_level_player(iPlayer)

// Sets the level to the player
native ls_set_level_player(iPlayer, Amount)

// Returns the player's current experience
native ls_get_exp_player(iPlayer)

// Sets the experience to the player
native ls_set_exp_player(iPlayer, Amount)

// Returns the maximum level
native ls_is_max_level()

// Returns the player's current bonuses
native ls_get_point_player(iPlayer)

// Sets bonuses to the player
native ls_set_point_player(iPlayer, Amount)

// Returns experience to the next level
native ls_exp_next_level(iPlayer)
